[service.home1]
hierarchy = "/org/freedesktop/home1"
id = "org.freedesktop.home1"
module = "home1"

[service.hostname1]
default_object = "Hostnamed"
hierarchy = "/org/freedesktop/hostname1"
id = "org.freedesktop.hostname1"
module = "hostname1"

[service.import1]
hierarchy = "/org/freedesktop/import1"
id = "org.freedesktop.import1"
module = "import1"

[service.locale1]
default_object = "Localed"
hierarchy = "/org/freedesktop/locale1"
id = "org.freedesktop.locale1"
module = "locale1"

[service.login1]
hierarchy = "/org/freedesktop/login1"
id = "org.freedesktop.login1"
module = "login1"

[service.machine1]
hierarchy = "/org/freedesktop/machine1"
id = "org.freedesktop.machine1"
module = "machine1"

[service.network1]
hierarchy = "/org/freedesktop/network1"
id = "org.freedesktop.network1"
module = "network1"

[service.oom1]
hierarchy = "/org/freedesktop/oom1"
id = "org.freedesktop.oom1"
module = "oom1"

[service.portable1]
hierarchy = "/org/freedesktop/portable1"
id = "org.freedesktop.portable1"
module = "portable1"

[service.resolve1]
hierarchy = "/org/freedesktop/resolve1"
id = "org.freedesktop.resolve1"
module = "resolve1"

[service.systemd1]
hierarchy = "/org/freedesktop/systemd1"
id = "org.freedesktop.systemd1"
module = "systemd1"

[service.timedate1]
default_object = "Timedated"
hierarchy = "/org/freedesktop/timedate1"
id = "org.freedesktop.timedate1"
module = "timedate1"
